#+TITLE: Eurorack module design - concepts

* Design principles

** General rules
   - Inputs should be able to survive indefinite exposure to +/- 12V
   - Outputs should be able to survive brief short to +/- 12V
   
** My preferences
   - Mini-pots are for setup, not performance
   - Every "performable" control should have CV.
     - Input attenuators and simple feedback loops don't need
       CV. (Just use a VCA.)
   - Sharing is interesting (1 CV -> many controls)
     - This is something that is cumbersome to wire up and
       space-saving in practice. A good motivation for a new module vs
       patching from building blocks.
   - CV inputs should have attenuators/attenuverters unless
     - they are V/oct or otherwise have an "obvious/correct" scaling
     - they are for gate signals (but adjustable threshold is nice)
     - the CV is more of an "input" than control, and output level is
       usefully related (e.g. sum, rectifier, ...)
   - Modular synths are about versatility. A module should either be
     - A fundamental building block
     - A collection of fundamental building blocks with normalled connections
     - Something that is very cumbersome/impossible to patch from
       fundamental building blocks.
       - Preferably, it can still be reduced to a fundamental block
   - Modules are much more useful when they work for both CV and
     audio. (i.e. avoid AC-coupling, avoid ADCs with low sampling rates.)

* Module concepts

** Comparator logic
   - Basic application: active gate combiner (e.g. multiple Euclidean
     sequences to one pattern)
   - Inspiration: As eurorack inputs pretty much require opamp
     buffers, a comparator is essentially "free".
   - A single VC threshold can be sent to multiple comparators, giving an
     interesting performance control.

   - Fundamental signal flow: 4x comparator -> OR logic -> OR/NOR outputs
     - Controls: Threshold
     - Inputs: 4x input, threshold
     - Outputs: OR gate, NOR gate

   Possible variations: XOR logic, inverted inputs
   - Initial idea was to use CMOS quad OR, which can be swapped for
     CMOS quad XOR. Two issues with that:
     - quad XOR is poorly defined
       - CD4030 has four 2-input XORs, these could be cascaded but
         resulting truth table is not obvious.

         | IN1 | IN2 | IN3 | IN4 | OUT |
         |-----+-----+-----+-----+-----|
         |   0 |   0 |   0 |   0 |   0 |
         |   1 |   0 |   0 |   0 |   1 |
         |   1 |   1 |   0 |   0 |   0 |
         |   1 |   1 |   1 |   0 |   1 |
         |   1 |   1 |   1 |   1 |   0 |
         |   1 |   1 |   1 |   0 |   1 |
         |   1 |   0 |   1 |   0 |   0 |
         |   1 |   0 |   1 |   1 |   1 |
         |   1 |   0 |   1 |   0 |   0 |

         ...

         That /seems/ to be "if (only one input is high) or (only one
         input is low)" which would do the job of making interesting
         patterns I guess.
   
     - quad OR chip is redundant once you've set up the unipolar input
       diodes; you can just sum them into output comparator.
   - Maybe we can have an analog switch between OR and XOR, or
     simultaneous outputs? (Need an extra chip either way; switch vs
     opamps. CD4016 quad switch is <50p so cost not an issue.)
   - Would be interesting to have one inverted input (using a spare
     NOT gate)
     - This needs to be normed to +Vss, otherwise OR will always be on
     - Could be switchable

   - Implementation notes:
     - Useful resource https://en.wikipedia.org/wiki/List_of_4000-series_integrated_circuits
     - Chips with lots of NOT gates on are helpful; as well as
       supplying logic for inverted input/output, remaining channels
       can be used to drive LEDs. (Can push/pull in parallel to get
       support higher current if needed.)
       - This could be a hex inverter 4069 / 40106, but 4041 quad
         buffer/inverter works very nicely with few wasted pins.

** Emphasis drive

   - Inspiration: emphasis-deemphasis processing (e.g. tape encoding)
     to bias nonlinear processes
   - This is difficult to do with standard modules as it requires a
     very well-matched pair of EQ/filter stages, linked frequency/q
     (if parametric) and inversely linked gain. Within a single module
     we can achieve that by sending CV to multiple destinations, with
     only (inverting) buffers between the split point and action.
   - The trouble is that we need four VCAs per filter band for VC
     polarisation in both "sides" of the process.
     - Workaround 1: use a single-band parametric EQ. That's usually
       enough in this application anyway.
     - Workaround 2: Fix one side as boost-only and the other as
       cut-only. If the user wants to reverse the order that can be
       done by patching.
   - A master emph/de-emph gain control would also be useful
     (gain-staging another module!)
     - Inverse-linking series unipolar VCAs could be tricky actually, do we need
       an exp converter for that?
   - To get the most out of this module you'll want to have a
     clipping/distortion stage. We might as well include one.
     - Tubescreamer-style soft-clipping with switchable diodes would be nice!
       - Would be quite cool to switch with a CD4016 but maybe
         overkill.  And not that useful with just two settings; maybe
         a cooler scheme is possible? Can also switch hard/soft
         clipping.
       - Could do that with a diode ladder to turn on successive
         switches. Would be very cool to go something like Si (soft)
         -> Si (Asymm) -> Ge (hard) -> Si (hard)
       - Easier to get working than a diode ladder might be an LM3916
         dot/bar display driver
         https://cdn.sparkfun.com/datasheets/Components/General%20IC/lm3916.pdf
         - Although it wants to regulate current flow, so
           high-impedence switch inputs might not be directly
           compatible. And it seems wasteful to drive current into
           ground. You can set the current with a reference load,
           though.  "Approximately 10 times this current will be drawn
           through each lighted LED" so a 1M load and 100k pull-downs
           should be ok.
         - At the very least the block diagram gives another way of
           doing this fairly precisely: using a resistor ladder with
           comparators. LM339 quad comparator maybe?
       - Shottky diodes can also be used for "soft-ish" hard clipping,
         might be easier to get hold of than Ge. Hard part will be
         picking diodes so that loudness isn't wildly different -
         should be able to somewhat compensate with resistors? Or
         multiple diodes in series.
       - If looking for more diodes, remember transistors and MOSFETs
         can also be used as diodes!
     - Hard clipping also simple to add if there's space to control it.
     - This can be fixed-gain if we already have a gain-staging
       control. But generally diode clipper headroom is a bit low for
       Eurorack so this section may need its own gain-staging
       amplifiers to be useful with typical VCOs.
   - An easy win on the implementation side: we need well-matched
     frequency tracking of four filter poles in order to achieve a
     pair of 6dB/8ve BP filters. This exists on a chip: SSI2140, which
     at £4 is an updated take on the classic SSM2040. CEM 3320 should
     also be able to do it.

** Fixed-band EQ

   - Inspiration: a 4-fixed-bands EQ was conceived as a nice user interface for an
     emphasis-de-emphasis module. It could then double as a nice tool
     to mix two overlapping mix elements by boosting and cutting
     sympathetically.
     - The trouble is that in a traditional cut/boost arrangement this
       would need 4 VCAs per band!
     - Alternatively we could remove the dry path and mix several
       broad bands. This would give a slightly lumpy frequency
       response, but that's not such a problem if it doesn't need to
       cancel with an inverse operation. I think this is how the Maag
       EQ4 works?
   - Interesting aspects: if we have CV attenuverters to each band's
     gain and norm them together, then a single CV input can be used
     to "morph" between different curves.
   - A nice feature of the Maag arrangement is that no master volume
     control is really needed; you can compensate volume by
     increasing/decreasing all the bands equally. (That is a lot
     easier to do with stepped controls, though.)
   - Implementation-wise, if we want a lot of clean EQ bands maybe
     digital is the way to go? An arduino should be able to handle the
     computation at a reasonable sample rate with RJB cookbook
     filters. We can limit the CV bandwidth to avoid aliasing, in
     which case the decent number of 16-bit ADC available should be
     sufficient.  The problem is the 12-bit outputs, I'd rather get to
     16-bit at least. Also, I don't see a lot of simple development
     environments for a low-HP device. Electrosmith Daisy Seed might
     be the best bet, but finding it harder than expected to get
     examples of Eurorack setup and DAC quality.
   - With analogue filters it would be fairly simple to also provide
     individual pre-VCA filter outputs. Is that useful? Would allow
     module to simultaneously act as a fixed multiband splitter. (And
     allow e.g. mid-high output to trigger envelope to low gain.)
     - Worth mentioning that quite a nice multiband splitter module
       exists in the form of LA61 LR4. This has VC crossovers and no
       mixing section - but of course would pair well with a (VC)
       mixer. No DIY version though!
     - Other than that, all I can find is a cheap fixed-band splitter
       from EMW and a presumably unobtainium 4-band VC Cwejman module.
     - I'm not really a huge fan of multi-band processing, but it does
       seem under-served. I guess people can use other filters
       anyway. Any SVF is a 2-band crossover, right?
   - A parallel soft-clipped output would be easy to include, making a
     tweakable distortion unit.
     - Depending on the complexity of CV scaling, we could get a master
       VCA quite "cheaply" that mixes extra CV into all bands

   - Hmm, just as this concept was coming together Boredbrain have
     announced a 10hp 5-band VC stereo EQ. Still seems worth working
     on this one: DIY, mono, smaller, broader, shift-switch is quite
     different overall. But this one must be absolutely stuffed with
     VCAs? Even if "balance" and "level" bias existing VCAs and
     crossovers are used to avoid need for subtraction, this is 10
     VCAs and a whole bunch of trimming/calibration. Or it's digital?

*** Proposed features/interface
    - 4-band EQ consisting of four parallel filter sections: LP,
      low-mid BP, high-mid BP, HP
      - Each filter has 6dB/octave (single-pole) slopes, creating a
        gentle set of crossovers. By spacing these correctly the
        response shouldn't be _too_ lumpy, but will be less
        transparent than a classic add/subtract EQ arrangement.
        - If the stages are obtained by subtracting a series of
          low-pass filters, then they _should_ be able to recombine
          perfectly?

    - Each band can be controlled manually or by CV, in the following
      scheme:
      - Each band has a CV input with full-sized attenuverter,
        normalled to the CV input above it. This allows a single CV
        input to e.g. cut lows and boost low-mid with intuitive
        controls.
      - Top CV is normalled to positive voltage, giving manual EQ when
        no CV is plugged in.
      - With 0V input, output is approximately unity.
      - Positive/negative input are approximately symmetric
        cuts/boosts in dB (i.e. gain changes on log-scale)
      - With all attenuverters at max/min, common input CV gives gain
        boost/cut with roughly flat frequency response.
      - Input CV range is +/- 5V, ok to clip beyond that

    - Bandpass filters have different bandwidths in order to
      achieve the most useful frequency selections. A useful shift
      in character could be achieved by using an analog switch to
      modify RC values. This would be the same direction for all
      modified values (i.e. no inverter needed to control this!)
      Values would be changed in pairs to keep crossovers aligned.
      - Move LP and lower limit of BP1 to change bass response
      - Move higher limit of BP1 and lower limit of BP2 for mids control
      - Move HP and higher limit of BP2 for different high response.

      Clearly the mids shift is especially useful. Not clear which
      is then the more useful of lows and highs: low shift is nice
      for kick/bass eq, but high shift may help make best use of
      upper-mid band after shifting.      

    - Panel:

      #+begin_example

         ---------
        |   Hi    |
        | 0---O   |
        | Hi-Mid  |
        | 0---O   |
        | Lo-Mid  |
        | 0---O   |
        |  Low    |
        | 0---O   |
        |  Shift  |
        | 0  -o   |
        |In  Out  |
        | 0 0 0 0 |
        |  VCA DST|
        |_________|

      #+end_example

    - This includes a few optional features. Suggest that initial
      prototype skips the master VCA and distortion output; see how we
      do for space/complexity. But these add whole extra functions for
      not many extra components, so worth considering.

*** Implementation details
    - VCAs mostly work with much lower unipolar control voltages, and
      more range on negative (attenuation) side
      - Some considerable offset/scaling effort is going to be needed
        to get from nice +/- 5V range to a safe VCA range with 0V
        unity. We'd like to make a healthy gain range available (at
        least +/- 18dB?) so assume that VCA is usually attenuating and
        makeup gain is supplied.
    - SSI Quad VCA chip looks very promising as this should give
      fairly consistent exponential control over four channels
      simultaneously. Might still need a bit of trimming? VCAs seem to
      need a lot of trimming in general...


** Rungler

   - Note that Rob Hordijk is quite protective of the Benjolin design;
     things based on rungling should not be disseminated too widely
     without asking nicely.
     - But I get the impression that homebrew DIY things are very much
       approved of...
   - Benjolin looks like a lot of fun, but I don't really need the
     extra oscillators and filter. A standalone rungler-like processor
     would let me patch a Benjolin with other modules.
   - Fancyyyyy Rung Divisions looks much more suitable; a combination
     of an enhanced rungler and clock divider. Unfortunately it's out
     of production. https://www.fancysynthesis.net/
     - A new version is imminent, but will be a wide module with knobs
       on. I really like module designs that don't need knobs.
   - Basically I want a 4hp module that is just the left-hand side of
     a Rung Divisions. The schematics are available so this shouldn't
     be too hard.
     - The RHS looks well cool, actually; clock divider with switchable
       OR bus. But it could be a separate module.
   - Apparently the successor to RD will have an expander for
     Klee-like sequencing. Something I really like about the Rung
     Divisions design already is that the multiple rungler outputs
     are, effectively, parallel pre-set Klee sequencers. There's
     probably room for more innovation in this area.
     - e.g. an analog switch and resistors could be used to make a
       CV-addressable set of "Klee presets"
     - But multiple parallel outputs is simpler and cooler?
       - How about a compromise: switchable variations on multiple
         outputs?
   - Modwiggler thread https://modwiggler.com/forum/viewtopic.php?t=155934
     - Consider option to break the XOR feedback loop, simplifying behaviour
     - Repeater shows a bare-bones version as part of instrument with
       2 VCOs, mixer and wavefolder
     - J3RK posts a really cool 8-stage design with LED indicators
       - Those would look cute arranged in a little 4hp ring!
       - Note that this isn't possible with the usual 4021 shift
         register chip, which only exposes the last 3 stages as
         outputs. https://www.ti.com/lit/ds/symlink/cd4021b.pdf
         J3RK uses a 4094 instead. (It's not like we were
         using the jam inputs anyway, and the chip price is about the
         same...) https://www.ti.com/lit/ds/symlink/cd4094b.pdf
         - Also this design uses a SIP resistor network. 4094 has the
           outputs in two groups of four, so this could be very tidy
           on stripboard!
       - and a bunch of other cool circuits
   - Electro-music thread on original Benjolin is interesting
     https://electro-music.com/forum/viewtopic.php?t=38081
     - Uses SSM2164 (quad VCA) for oscillator core. Gets the
       exponential scaling for free.

   - Possible panel elements:
     - Inputs: clock, data, reset
       - What does reset do to a manually-programmed sequence? Is
         there any way to set up a shorter sequence with an 8-bit SR?
         Move feedback point?

     - Knobs: threshold, random

     - Switches/buttons: write, clear, XOR feedback, manual clock
       - (on)/off/(on) write/clear momentary toggle could work by
         setting data comparator threshold; that isolates it from
         input jack.
       - Manual clock button not generally found on these things but
         would be useful

     - Feedback: 678 LEDs, LED ring, LED ring w/ 678 in another
       colour, LED strip

     - Outputs: Bits 6, 7, 8, RUNG, GNUR, XOR
   
** Bussed clock divider
   - NLC's Divide and Conquer is very cool (fractional values!) but
     lacks reset inputs.
   - The right-hand side of Rung Divisions has a nice bus-switching
     setup to direct clock dividers into a common OR stream.
   - Could toggle between two different busses with SP3T switches,
     like a switched mult.
     - Is that actually useful though? Wouldn't you often want a
       division to appear in both?
     - With so many switches and ICs, might be an idea to _not_
       provide individual outputs
   - Would be nice to have logic other than OR... but how?
     - For AND, could have all unselected streams normed to "high"
     - For XOR, would need each selected stream to add a XOR stage to
       bus.
     - Some of those would need a few poles, perhaps using analog
       switch ICs?
       - This could add up to a lot of ICs...

** Clippers/waveshapers
   - Made a nice simple morphable shaper at https://tinyurl.com/ygknmmxr
     - it's just a hard clipper subtracted from a soft clipper, with
       variable gain on the hard clipper
     - Mixing and VCAs are things people have in their rack
       already. Simple DC-couple clippers are not.
   - How about a simple 4hp 8-jack module with 4 inputs (normalised
     together for easy parallel processing) and 4 outputs with
     different clippers?
     - Soft-clipping (feedback diodes)
     - Hard-clipping (Silicon, Ge, Zener?)
     - Opamp rail clipping (is this qualitatively different?)
     - Clean boost
     - OML Sinecore sine-shaper-on-a-chip
     - Saw-to-triangle function: either a full rectifier or triangle folder
     - Panel accessible-trimpots would be great for setting gain
   - Fixed gain based on +/- 5V is good for oscillator shaping and
     accessible to other stuff.
     - A clean boost (output-compensated?) would be rather useful
       anyway. Could be on a toggle switch?
   - Another interesting element of modular waveshapers, which is not
     generally accessible, are the diode ladders used in wave folding.
     If you provided access to each stage they could be patched into a
     customisable wavefolder!
     - Could also send them to +/- sum via on/off/on switches. Then
       you can e.g. set high values to "off" for clipping, low values
       "off" for fuzz, and create more folds with alternating +/-

       #+begin_example
        _____________
       | BYO WAVEFOLD|
       | IN  +/off/- |
       |  0          |
       |  1          |
       |  0 ->  o-   |
       |  2     |    |
       |  0 -> -o    |
       |  3     |    |
       |  0 ->  o-   |
       |  4     |    |
       |  0 -> -o    |
       |  5     |    |
       |  0 ->  o-   |
       |  6     |    |
       |  0 -> -o    |
       | GAIN   |MIX |
       |  0     0    |
       |_____________|

       #+end_example

       Ticks a lot of boxes! No pots, can break out for other purposes
       (e.g. splitting CV to multiple destinations), sensible default
       gain which can be manipulated by CV. 4hp theoretically possible
       but tight, 6hp would be more resonable. Needs one VCA and a lot
       of opamps. (Input/VCA section, 6 section output buffers, output
       mixer.) Output mixer would /normally/ be done by mixing between
       two inverting opamps in series, but it should also work to use
       both inputs of one opamp?

       Maybe skip the VCA, it's just on the input anyway. People have
       VCAs already... But add a bit of fixed gain? Could set with a
       jumper.

*** Clipper/splitter circuit
    - Proving more difficult than expected to get this hard-clipping
      topology to work nicely
      - LEDs might be the best clipping diode: high threshold
        voltage and gives quite a sharp corner. (Red LED gives 1.5-2.0V drop)
      - Another idea would be to use op-amp clipping. No need for
        extra diodes, but a bit more gain-staging needed. (Inputs
        should not clip to avoid TL072 phase inversion, so we go in
        quiet, apply some gain to clip output, then compensate with
        voltage divider.)
        - Could lower headroom with a different voltage supply, but
          that exacerbates phase-inversion so no real benefit
    - Here's a proof of concept in circuitjs:
      https://falstad.com/circuit/circuitjs.html?ctz=CQAgjCAMB0l3BWcMBMcUHYMGZIA4UA2ATmIxAUgoqoQFMBaMMAKACUQAWbFEHq-nzRQ+XWiKowELAIZdCnPtkIUMK7MpDFwSJkjDx4faMULZTkFMQIIwCQpCTYTZ0qWwY8CTt+zJDLADu8orYCLycCmKSQSHRqiqccFCxCGrxaeqakLGRocLcvII5AE5cPEJUhfFUBgEA5uURydXVMcEKApqdfIR4KR1Jvf2EGEV9KQAmID3KI0PVvJN0AGYyAK4ANgAuDJt0kyzToxEVJ8MgS6sbO3sHsefVPW0sjc9nC3iSKWWZSiqzbL+HLBDCQUITc5zAYgPBgRKcfpw9R4RQgkBgxScRGw+FcHHozHxInY-ro5F8VGwr6UtEsJJ+FAoUJUsIRAlQAD6Ck5kE5SWsnIQvNg8DIhHsKGFfJQvM52HpkD8UPBsOS0NqhG5nDlAuInJQ0Glorg4sl0oNnPh8pYZTwNOwVPFtJEdRycmd0IM9ou2jsID0wKMzlMjrIPjAnAwxFsCH6IdcDisNjsDn0hnRnqd6RewW9-Wq+YupS0OYqRbawNkGNVjsUFLrWh0Af9bqMYGgCmwzDU1nCkGYMfAne4YGwnDAVhIGAMUaD6L+GhUfxQPoX6VX-Wdm5h259nvCKQZyGZlzG4DsRSBUu1usgpCtfJgcEIN5lBuFCuCFNJuOXxF4EsKQQACtAcChQNqDNYgrct8H6EDANtZAfUQsDaEg+dYgsCDeBw85M3A846hGc93X8EYfWYbofX6f1AzbZJn3gaNMAQNJIDUZlRmxV1oLzOBSN4EiZiGEsRJ6aiATErC8zHaTankmY11eCia0UESMEPdoLxoui0CoPoyUVPwpIxYRJyiTw0XKW8+T1R8RUMM1XwtWVuBtIA
      - Better version now in falstad folder

    - Another interesting clipping topology: VC one-sided hard clip
      https://www.tutorialspoint.com/linear_integrated_circuits_applications/linear_integrated_circuits_applications_clippers.htm
      - Compared to a TS-style soft clipper, we take the output
        _after_ the feedback diode.
      - I don't see an easy way to make this two-sided, but it gives a
        lovely hard clip (as output is pulled to Vref)

** Unipolar/bipolar shifter

   - An interesting circuit related to a clipper that I haven't really
     seen in Eurorack is the /clamper/. This uses a capacitor,
     resistor and diode to collect a bias voltage whenever the signal
     exceeds the diode forward-voltage. Because the effect is damped
     by the capacitor, this doesn't have to cause distortion: it
     shifts a bipolar signal to a unipolar one (+/- an input bias).
     https://electronicsreference.com/analog/clamper_circuit/
   - Of course, converting from unipolar to bipolar is just a very
     low-frequency RC high-pass filter.

   - Could be useful to change the time constant to suit a given input
     signal. At very small time constants we'll get distortion, with
     large time constants it will react slowly.

   - Easy to VC the reference point, but how useful is that? Basically
     an offset control, could also be achived by mixing output.
     - Might make an interesting distortion at audio rate?

   - For modules that only take +ve CV input this could be a nice
     supporting utility. Do I have any of those? Good for VCA/LPG
     signals?
     - Could use at CV input section of an Ardiuno-based module to
       intelligently handle both unipolar and bipolar inputs. Could be
       a bit confusing if unexpected though.

** Ultrasonic processing

   - Several interesting processes can be clocked by an ultrasonic
     oscillator, e.g.
     - mod-demod audio encoding
     - NLC digital filter simulator
     - Switched-cap filter (implemented in the LTC1064 chip)
       - Fabrica does it with a 4066 - what rate limit does that impose?
         https://github.com/vauxflores/Electronics/tree/master/Eurorack/Fabrica
       - CD4066B datasheet mentions control repetitions in MHz and
         "propogation delay" of around 20 ns - so should be just about
         fast enough for glitches to not dominate behaviour?
       - The technical purpose of switched-cap filters is for
         implementing very steep filters at accurate, high
         frequencies. They absolutely can go to lower frequencies, but
         the clock is running at 50x the cutoff frequency which is
         audible for low frequencies. Could also get aliasing?
     - Sampling processors: Sample/hold, shift register, "rungling"
       - Especially Squid Axon with its four clocks per new sample...
       - Can generate intentional aliasing by resampling at audio rate
         without a filter
     - Delta-sigma modulation (i.e. "1-bit" ADC/DAC)
   - Would be nice to have proper V/octave control over these so they
     can be related to audible VCO frequencies.
     - Or use a frequency multiplier? CD4046B phase-locked loop VCO
       can go up to 1.2 MHz.
       - It might make a lot of sense to use a CD4046B as the main VCO
         source actually. It's cheap and voltage-controllable.
   - This whole class of processing falls squarely into "hard to do
     in-the-box", which is really what I'm interested in modular for
     :-D
     - That being said, some oversampled Reaktor simulations might
       help with dialing in useful parameter ranges...
   - An interesting thing to introduce to this stuff in general is
     jitter. What's the best way to introduce small timing
     inconsistencies to a square wave oscillator?
   - For some switched-capacitor/resistor arrangements we can manipulate the effective value with the /pulse width/ of the switching.
     - A single high-frequency sawtooth clock could drive multiple filters using (relatively cheap/simple) VC comparators.
     - That seems like a great source of multiple somewhat lofi VCFs. What could we do with those?
   - Nearest thing out there seems to be WMD synchrodyne, which
     implements VCO -> PLL -> switched-cap filter
     - In practice the character/workflow is rather dominated by wobbly PLL wrangling
     - As usual for WMD, the module has tight control spacing and is a tad pricy at ~£350-400
     - Still, it seems like a pretty comprehensive take on placing
       that chain under VC. Good stuff, no point in going the same way.
   - It may be a bad idea to send ultrasonic signals through Eurorack
     inputs/outputs. The format is not really engineered for
     them. Generally the advice with HF is to keep paths very short in
     order to a) avoid capacitative losses b) avoid crosstalk with
     your other stuff.
     - The synchrodyne allows an external clock for the PLL but not
       for the filter. It does allow PLL output, but that has a wide
       useful range.
     - Maybe near-ultrasound is fine. But radio is not far
       away... (Strictly speaking, audio range is Very Low Frequency
       (VLF) radio.)
   - Barton SRV is a PWM-based filter, providing two resonant SVFs
     with multiple outputs.
     https://www.bartonmusicalcircuits.com/srv/ There is an inbuilt
     fixed oscillator and external clock input. Very nice!
     - Switched-resistor rather than switched-capacitor
       - The two are not so different really; switched-capacitors also
         replace resistors.
     - Demo vid suggests the LPF doesn't really "close" completely?
       Should be tweakable.
     - Audio-rate clock vowel sound demo is rad. I should build one of
       these.
   - PWM control seems an interesting general alternative to a vactrol
     or VCA. How about a PWM VCA? Presumably this is how PWM
     compressors work?
     - For a PWM VCA, just send the input signal through the
       PWM-controlled switch. At zero pulse-width you have a perfect
       "off" state. At 50:50 you have half gain, so will need some
       makeup.
     - What about nonlinear elements? Would this be one way to make a
       morphable transfer function?
