#+TITLE: Eurorack module design - concepts

* Design principles

** General rules
   - Inputs should be able to survive indefinite exposure to +/- 12V
   - Outputs should be able to survive brief short to +/- 12V
   
** My preferences
   - Mini-pots are for setup, not performance
   - Every "performable" control should have CV.
     - Input attenuators and simple feedback loops don't need
       CV. (Just use a VCA.)
   - Sharing is interesting (1 CV -> many controls)
     - This is something that is cumbersome to wire up and
       space-saving in practice. A good motivation for a new module vs
       patching from building blocks.
   - CV inputs should have attenuators/attenuverters unless
     - they are V/oct or otherwise have an "obvious/correct" scaling
     - they are for gate signals (but adjustable threshold is nice)
     - the CV is more of an "input" than control, and output level is
       usefully related (e.g. sum, rectifier, ...)
   - Modular synths are about versatility. A module should either be
     - A fundamental building block
     - A collection of fundamental building blocks with normalled connections
     - Something that is very cumbersome/impossible to patch from
       fundamental building blocks.
       - Preferably, it can still be reduced to a fundamental block
   - Modules are much more useful when they work for both CV and
     audio. (i.e. avoid AC-coupling, avoid ADCs with low sampling rates.)

* Some interesting building blocks
  - This paper reports a voltage multiplier (i.e. ring mod) using 3 op-amps.
    http://nopr.niscair.res.in/bitstream/123456789/6896/1/IJPAP%2048%281%29%2067-70.pdf

* Module concepts

** Comparator logic
   - Basic application: active gate combiner (e.g. multiple Euclidean
     sequences to one pattern)
   - Inspiration: As eurorack inputs pretty much require opamp
     buffers, a comparator is essentially "free".
   - A single VC threshold can be sent to multiple comparators, giving an
     interesting performance control.

   - Fundamental signal flow: 4x comparator -> OR logic -> OR/NOR outputs
     - Controls: Threshold
     - Inputs: 4x input, threshold
     - Outputs: OR gate, NOR gate

   Possible variations: XOR logic, inverted inputs
   - Initial idea was to use CMOS quad OR, which can be swapped for
     CMOS quad XOR. Two issues with that:
     - quad XOR is poorly defined
       - CD4030 has four 2-input XORs, these could be cascaded but
         resulting truth table is not obvious.

         | IN1 | IN2 | IN3 | IN4 | OUT |
         |-----+-----+-----+-----+-----|
         |   0 |   0 |   0 |   0 |   0 |
         |   1 |   0 |   0 |   0 |   1 |
         |   1 |   1 |   0 |   0 |   0 |
         |   1 |   1 |   1 |   0 |   1 |
         |   1 |   1 |   1 |   1 |   0 |
         |   1 |   1 |   1 |   0 |   1 |
         |   1 |   0 |   1 |   0 |   0 |
         |   1 |   0 |   1 |   1 |   1 |
         |   1 |   0 |   1 |   0 |   0 |

         ...

         That /seems/ to be "if (only one input is high) or (only one
         input is low)" which would do the job of making interesting
         patterns I guess.
   
     - quad OR chip is redundant once you've set up the unipolar input
       diodes; you can just sum them into output comparator.
   - Maybe we can have an analog switch between OR and XOR, or
     simultaneous outputs? (Need an extra chip either way; switch vs
     opamps. CD4016 quad switch is <50p so cost not an issue.)
   - Would be interesting to have one inverted input (using a spare
     NOT gate)
     - This needs to be normed to +Vss, otherwise OR will always be on
     - Could be switchable

   - Implementation notes:
     - Useful resource https://en.wikipedia.org/wiki/List_of_4000-series_integrated_circuits
     - Chips with lots of NOT gates on are helpful; as well as
       supplying logic for inverted input/output, remaining channels
       can be used to drive LEDs. (Can push/pull in parallel to get
       support higher current if needed.)
       - This could be a hex inverter 4069 / 40106, but 4041 quad
         buffer/inverter works very nicely with few wasted pins.

   - Common-mode voltage reversal is a concern for TL072 etc. Possible
     that module will get some hot negative inputs on both
     sides. Possible precautions:
     - Scale down inputs with voltage divider - costs precision
     - clip inputs with 10V ESD zeners - costs range (and money)
     - use MCP6002/MCP6004 instead; these opamps are also cheap and
       designed for rail-to-rail inputs.
       - datasheet says they only go to 6V? bah.
       - LM324 should do the trick
         - Trouble with LM324 is BJT input stage needs current; with
           100k input impedence accuracy takes a hit.
           - As long as it's consistent channel-to-channel that could
             be fine in this application?

** Emphasis drive

   - Inspiration: emphasis-deemphasis processing (e.g. tape encoding)
     to bias nonlinear processes
   - This is difficult to do with standard modules as it requires a
     very well-matched pair of EQ/filter stages, linked frequency/q
     (if parametric) and inversely linked gain. Within a single module
     we can achieve that by sending CV to multiple destinations, with
     only (inverting) buffers between the split point and action.
   - The trouble is that we need four VCAs per filter band for VC
     polarisation in both "sides" of the process.
     - Workaround 1: use a single-band parametric EQ. That's usually
       enough in this application anyway.
     - Workaround 2: Fix one side as boost-only and the other as
       cut-only. If the user wants to reverse the order that can be
       done by patching.
   - A master emph/de-emph gain control would also be useful
     (gain-staging another module!)
     - Inverse-linking series unipolar VCAs could be tricky actually, do we need
       an exp converter for that?
   - To get the most out of this module you'll want to have a
     clipping/distortion stage. We might as well include one.
     - Tubescreamer-style soft-clipping with switchable diodes would be nice!
       - Would be quite cool to switch with a CD4016 but maybe
         overkill.  And not that useful with just two settings; maybe
         a cooler scheme is possible? Can also switch hard/soft
         clipping.
       - Could do that with a diode ladder to turn on successive
         switches. Would be very cool to go something like Si (soft)
         -> Si (Asymm) -> Ge (hard) -> Si (hard)
       - Easier to get working than a diode ladder might be an LM3916
         dot/bar display driver
         https://cdn.sparkfun.com/datasheets/Components/General%20IC/lm3916.pdf
         - Although it wants to regulate current flow, so
           high-impedence switch inputs might not be directly
           compatible. And it seems wasteful to drive current into
           ground. You can set the current with a reference load,
           though.  "Approximately 10 times this current will be drawn
           through each lighted LED" so a 1M load and 100k pull-downs
           should be ok.
         - At the very least the block diagram gives another way of
           doing this fairly precisely: using a resistor ladder with
           comparators. LM339 quad comparator maybe?
       - Shottky diodes can also be used for "soft-ish" hard clipping,
         might be easier to get hold of than Ge. Hard part will be
         picking diodes so that loudness isn't wildly different -
         should be able to somewhat compensate with resistors? Or
         multiple diodes in series.
       - If looking for more diodes, remember transistors and MOSFETs
         can also be used as diodes!
     - Hard clipping also simple to add if there's space to control it.
     - This can be fixed-gain if we already have a gain-staging
       control. But generally diode clipper headroom is a bit low for
       Eurorack so this section may need its own gain-staging
       amplifiers to be useful with typical VCOs.
   - An easy win on the implementation side: we need well-matched
     frequency tracking of four filter poles in order to achieve a
     pair of 6dB/8ve BP filters. This exists on a chip: SSI2140, which
     at £4 is an updated take on the classic SSM2040. CEM 3320 should
     also be able to do it.

** Fixed-band EQ

   - Inspiration: a 4-fixed-bands EQ was conceived as a nice user interface for an
     emphasis-de-emphasis module. It could then double as a nice tool
     to mix two overlapping mix elements by boosting and cutting
     sympathetically.
     - The trouble is that in a traditional cut/boost arrangement this
       would need 4 VCAs per band!
     - Alternatively we could remove the dry path and mix several
       broad bands. This would give a slightly lumpy frequency
       response, but that's not such a problem if it doesn't need to
       cancel with an inverse operation. I think this is how the Maag
       EQ4 works?
   - Interesting aspects: if we have CV attenuverters to each band's
     gain and norm them together, then a single CV input can be used
     to "morph" between different curves.
   - A nice feature of the Maag arrangement is that no master volume
     control is really needed; you can compensate volume by
     increasing/decreasing all the bands equally. (That is a lot
     easier to do with stepped controls, though.)
   - Implementation-wise, if we want a lot of clean EQ bands maybe
     digital is the way to go? An arduino should be able to handle the
     computation at a reasonable sample rate with RJB cookbook
     filters. We can limit the CV bandwidth to avoid aliasing, in
     which case the decent number of 16-bit ADC available should be
     sufficient.  The problem is the 12-bit outputs, I'd rather get to
     16-bit at least. Also, I don't see a lot of simple development
     environments for a low-HP device. Electrosmith Daisy Seed might
     be the best bet, but finding it harder than expected to get
     examples of Eurorack setup and DAC quality.
   - With analogue filters it would be fairly simple to also provide
     individual pre-VCA filter outputs. Is that useful? Would allow
     module to simultaneously act as a fixed multiband splitter. (And
     allow e.g. mid-high output to trigger envelope to low gain.)
     - Worth mentioning that quite a nice multiband splitter module
       exists in the form of LA61 LR4. This has VC crossovers and no
       mixing section - but of course would pair well with a (VC)
       mixer. No DIY version though!
     - Other than that, all I can find is a cheap fixed-band splitter
       from EMW and a presumably unobtainium 4-band VC Cwejman module.
     - I'm not really a huge fan of multi-band processing, but it does
       seem under-served. I guess people can use other filters
       anyway. Any SVF is a 2-band crossover, right?
   - A parallel soft-clipped output would be easy to include, making a
     tweakable distortion unit.
     - Depending on the complexity of CV scaling, we could get a master
       VCA quite "cheaply" that mixes extra CV into all bands

   - Hmm, just as this concept was coming together Boredbrain have
     announced a 10hp 5-band VC stereo EQ. Still seems worth working
     on this one: DIY, mono, smaller, broader, shift-switch is quite
     different overall. But this one must be absolutely stuffed with
     VCAs? Even if "balance" and "level" bias existing VCAs and
     crossovers are used to avoid need for subtraction, this is 10
     VCAs and a whole bunch of trimming/calibration. Or it's digital?

*** Proposed features/interface
    - 4-band EQ consisting of four parallel filter sections: LP,
      low-mid BP, high-mid BP, HP
      - Each filter has 6dB/octave (single-pole) slopes, creating a
        gentle set of crossovers. By spacing these correctly the
        response shouldn't be _too_ lumpy, but will be less
        transparent than a classic add/subtract EQ arrangement.
        - If the stages are obtained by subtracting a series of
          low-pass filters, then they _should_ be able to recombine
          perfectly?

    - Each band can be controlled manually or by CV, in the following
      scheme:
      - Each band has a CV input with full-sized attenuverter,
        normalled to the CV input above it. This allows a single CV
        input to e.g. cut lows and boost low-mid with intuitive
        controls.
      - Top CV is normalled to positive voltage, giving manual EQ when
        no CV is plugged in.
      - With 0V input, output is approximately unity.
      - Positive/negative input are approximately symmetric
        cuts/boosts in dB (i.e. gain changes on log-scale)
      - With all attenuverters at max/min, common input CV gives gain
        boost/cut with roughly flat frequency response.
      - Input CV range is +/- 5V, ok to clip beyond that

    - Bandpass filters have different bandwidths in order to
      achieve the most useful frequency selections. A useful shift
      in character could be achieved by using an analog switch to
      modify RC values. This would be the same direction for all
      modified values (i.e. no inverter needed to control this!)
      Values would be changed in pairs to keep crossovers aligned.
      - Move LP and lower limit of BP1 to change bass response
      - Move higher limit of BP1 and lower limit of BP2 for mids control
      - Move HP and higher limit of BP2 for different high response.

      Clearly the mids shift is especially useful. Not clear which
      is then the more useful of lows and highs: low shift is nice
      for kick/bass eq, but high shift may help make best use of
      upper-mid band after shifting.      

    - Panel:

      #+begin_example

         ---------
        |   Hi    |
        | 0---O   |
        | Hi-Mid  |
        | 0---O   |
        | Lo-Mid  |
        | 0---O   |
        |  Low    |
        | 0---O   |
        |  Shift  |
        | 0  -o   |
        |In  Out  |
        | 0 0 0 0 |
        |  VCA DST|
        |_________|

      #+end_example

    - This includes a few optional features. Suggest that initial
      prototype skips the master VCA and distortion output; see how we
      do for space/complexity. But these add whole extra functions for
      not many extra components, so worth considering.

*** Implementation details
    - VCAs mostly work with much lower unipolar control voltages, and
      more range on negative (attenuation) side
      - Some considerable offset/scaling effort is going to be needed
        to get from nice +/- 5V range to a safe VCA range with 0V
        unity. We'd like to make a healthy gain range available (at
        least +/- 18dB?) so assume that VCA is usually attenuating and
        makeup gain is supplied.
    - SSI Quad VCA chip looks very promising as this should give
      fairly consistent exponential control over four channels
      simultaneously. Might still need a bit of trimming? VCAs seem to
      need a lot of trimming in general...


** Multi-mode filter
   - Interesting document from SSI describes filter design with the
     SSI2164 quad VCA. http://www.soundsemiconductor.com/downloads/AN701.pdf
   - Table 1 shows how the stages of a cascaded 4-pole LP filter can
     be combined in different ratios to obtain many different filter
     responses (including HP, BP, AP).
   - Massively-multimode filters like the Polaris might use this sort
     of scheme with a microcontroller and analog switch ICs to toggle
     different arrangements.
   - In principle you could run all these inputs into a mixer to dial
     in custom filter responses.
     - This is another case where a VC morphing mixer would be
       useful. Maybe that should be its own module, and then the
       filter component is just a 4-pole LP with stage outputs?
     - 5 stages could be a bit tricky to handle, is there a useful
       macro/gang option to make this control space more manageable?
       - Could prototype that in Reaktor?
     - 4 is a much nicer number when it comes to VCAs, opamps etc...
   - Is there any reason you couldn't do the same thing with SSI2140?
     Would that be easier? We don't need independent frequency control
     in this application.

** Rungler

   - Note that Rob Hordijk is quite protective of the Benjolin design;
     things based on rungling should not be disseminated too widely
     without asking nicely.
     - But I get the impression that homebrew DIY things are very much
       approved of...
   - Benjolin looks like a lot of fun, but I don't really need the
     extra oscillators and filter. A standalone rungler-like processor
     would let me patch a Benjolin with other modules.
   - Fancyyyyy Rung Divisions looks much more suitable; a combination
     of an enhanced rungler and clock divider. Unfortunately it's out
     of production. https://www.fancysynthesis.net/
     - A new version is imminent, but will be a wide module with knobs
       on. I really like module designs that don't need knobs.
   - Basically I want a 4hp module that is just the left-hand side of
     a Rung Divisions. The schematics are available so this shouldn't
     be too hard.
     - The RHS looks well cool, actually; clock divider with switchable
       OR bus. But it could be a separate module.
   - Apparently the successor to RD will have an expander for
     Klee-like sequencing. Something I really like about the Rung
     Divisions design already is that the multiple rungler outputs
     are, effectively, parallel pre-set Klee sequencers. There's
     probably room for more innovation in this area.
     - e.g. an analog switch and resistors could be used to make a
       CV-addressable set of "Klee presets"
     - But multiple parallel outputs is simpler and cooler?
       - How about a compromise: switchable variations on multiple
         outputs?
   - Modwiggler thread https://modwiggler.com/forum/viewtopic.php?t=155934
     - Consider option to break the XOR feedback loop, simplifying behaviour
     - Repeater shows a bare-bones version as part of instrument with
       2 VCOs, mixer and wavefolder
     - J3RK posts a really cool 8-stage design with LED indicators
       - Those would look cute arranged in a little 4hp ring!
       - Note that this isn't possible with the usual 4021 shift
         register chip, which only exposes the last 3 stages as
         outputs. https://www.ti.com/lit/ds/symlink/cd4021b.pdf
         J3RK uses a 4094 instead. (It's not like we were
         using the jam inputs anyway, and the chip price is about the
         same...) https://www.ti.com/lit/ds/symlink/cd4094b.pdf
         - Also this design uses a SIP resistor network. 4094 has the
           outputs in two groups of four, so this could be very tidy
           on stripboard!
       - and a bunch of other cool circuits
   - Electro-music thread on original Benjolin is interesting
     https://electro-music.com/forum/viewtopic.php?t=38081
     - Uses SSM2164 (quad VCA) for oscillator core. Gets the
       exponential scaling for free.

   - Possible panel elements:
     - Inputs: clock, data, reset
       - What does reset do to a manually-programmed sequence? Is
         there any way to set up a shorter sequence with an 8-bit SR?
         Move feedback point?

     - Knobs: threshold, random

     - Switches/buttons: write, clear, XOR feedback, manual clock
       - (on)/off/(on) write/clear momentary toggle could work by
         setting data comparator threshold; that isolates it from
         input jack.
       - Manual clock button not generally found on these things but
         would be useful

     - Feedback: 678 LEDs, LED ring, LED ring w/ 678 in another
       colour, LED strip

     - Outputs: Bits 6, 7, 8, RUNG, GNUR, XOR

   - A lot of what I want can be done with NLC 8-bit cipher. There is
     something to be said for simplifying the sequencing/Turing
     Machine workflow, but maybe I should build one of those and spend
     time with it before returning to this idea.
   
** Bussed clock divider
   - NLC's Divide and Conquer is very cool (fractional values!) but
     lacks reset inputs.
   - The right-hand side of Rung Divisions has a nice bus-switching
     setup to direct clock dividers into a common OR stream.
   - Could toggle between two different busses with SP3T switches,
     like a switched mult.
     - Is that actually useful though? Wouldn't you often want a
       division to appear in both?
     - With so many switches and ICs, might be an idea to _not_
       provide individual outputs
   - Would be nice to have logic other than OR... but how?
     - For AND, could have all unselected streams normed to "high"
     - For XOR, would need each selected stream to add a XOR stage to
       bus.
     - Some of those would need a few poles, perhaps using analog
       switch ICs?
       - This could add up to a lot of ICs...

** Clippers/waveshapers
   - Made a nice simple morphable shaper at https://tinyurl.com/ygknmmxr
     - it's just a hard clipper subtracted from a soft clipper, with
       variable gain on the hard clipper
     - Mixing and VCAs are things people have in their rack
       already. Simple DC-couple clippers are not.

    - Proving more difficult than expected to get this hard-clipping
      topology to work nicely
      - LEDs might be the best clipping diode: high threshold
        voltage and gives quite a sharp corner. (Red LED gives 1.5-2.0V drop)
      - Another idea would be to use op-amp clipping. No need for
        extra diodes, but a bit more gain-staging needed. (Inputs
        should not clip to avoid TL072 phase inversion, so we go in
        quiet, apply some gain to clip output, then compensate with
        voltage divider.)
        - Could lower headroom with a different voltage supply, but
          that exacerbates phase-inversion so no real benefit
    - Here's a proof of concept in circuitjs:
      https://falstad.com/circuit/circuitjs.html?ctz=CQAgjCAMB0l3BWcMBMcUHYMGZIA4UA2ATmIxAUgoqoQFMBaMMAKACUQAWbFEHq-nzRQ+XWiKowELAIZdCnPtkIUMK7MpDFwSJkjDx4faMULZTkFMQIIwCQpCTYTZ0qWwY8CTt+zJDLADu8orYCLycCmKSQSHRqiqccFCxCGrxaeqakLGRocLcvII5AE5cPEJUhfFUBgEA5uURydXVMcEKApqdfIR4KR1Jvf2EGEV9KQAmID3KI0PVvJN0AGYyAK4ANgAuDJt0kyzToxEVJ8MgS6sbO3sHsefVPW0sjc9nC3iSKWWZSiqzbL+HLBDCQUITc5zAYgPBgRKcfpw9R4RQgkBgxScRGw+FcHHozHxInY-ro5F8VGwr6UtEsJJ+FAoUJUsIRAlQAD6Ck5kE5SWsnIQvNg8DIhHsKGFfJQvM52HpkD8UPBsOS0NqhG5nDlAuInJQ0Glorg4sl0oNnPh8pYZTwNOwVPFtJEdRycmd0IM9ou2jsID0wKMzlMjrIPjAnAwxFsCH6IdcDisNjsDn0hnRnqd6RewW9-Wq+YupS0OYqRbawNkGNVjsUFLrWh0Af9bqMYGgCmwzDU1nCkGYMfAne4YGwnDAVhIGAMUaD6L+GhUfxQPoX6VX-Wdm5h259nvCKQZyGZlzG4DsRSBUu1usgpCtfJgcEIN5lBuFCuCFNJuOXxF4EsKQQACtAcChQNqDNYgrct8H6EDANtZAfUQsDaEg+dYgsCDeBw85M3A846hGc93X8EYfWYbofX6f1AzbZJn3gaNMAQNJIDUZlRmxV1oLzOBSN4EiZiGEsRJ6aiATErC8zHaTankmY11eCia0UESMEPdoLxoui0CoPoyUVPwpIxYRJyiTw0XKW8+T1R8RUMM1XwtWVuBtIA
      - Better version now in falstad folder

    - Another interesting clipping topology: VC one-sided hard clip
      https://www.tutorialspoint.com/linear_integrated_circuits_applications/linear_integrated_circuits_applications_clippers.htm
      - Compared to a TS-style soft clipper, we take the output
        _after_ the feedback diode.
      - I don't see an easy way to make this two-sided, but it gives a
        lovely hard clip (as output is pulled to Vref)


*** Clipper/splitter circuit
   - Another interesting element of modular waveshapers, which is not
     generally accessible, are the diode ladders used in wave folding.
     If you provided access to each stage they could be patched into a
     customisable wavefolder!
     - Could also send them to +/- sum via on/off/on switches. Then
       you can e.g. set high values to "off" for clipping, low values
       "off" for fuzz, and create more folds with alternating +/-

       #+begin_example
        _____________
       | BYO WAVEFOLD|
       | IN  +/off/- |
       |  0          |
       |  1          |
       |  0 ->  o-   |
       |  2     |    |
       |  0 -> -o    |
       |  3     |    |
       |  0 ->  o-   |
       |  4     |    |
       |  0 -> -o    |
       |  5     |    |
       |  0 ->  o-   |
       |  6     |    |
       |  0 -> -o    |
       | GAIN   |MIX |
       |  0     0    |
       |_____________|

       #+end_example

       Ticks a lot of boxes! No pots, can break out for other purposes
       (e.g. splitting CV to multiple destinations), sensible default
       gain which can be manipulated by CV. 4hp theoretically possible
       but tight, 6hp would be more resonable. Needs one VCA and a lot
       of opamps. (Input/VCA section, 6 section output buffers, output
       mixer.) Output mixer would /normally/ be done by mixing between
       two inverting opamps in series, but it should also work to use
       both inputs of one opamp?

       Maybe skip the VCA, it's just on the input anyway. People have
       VCAs already... But add a bit of fixed gain? Could set with a
       jumper.


*** Clipping pallette

   - How about a simple module with 4-6 inputs (normalised
     together for easy parallel processing) and outputs with
     different clippers?
     - Soft-clipping (feedback diodes)
     - Hard-clipping (Silicon, Ge, Zener?)
     - Opamp rail clipping (is this qualitatively different?)
     - Clean boost
     - OML Sinecore sine-shaper-on-a-chip
     - Saw-to-triangle function: either a full rectifier or triangle folder
     - Panel accessible-trimpots would be great for setting gain
   - Fixed gain based on +/- 5V is good for oscillator shaping and
     accessible to other stuff.
     - A clean boost (output-compensated?) would be rather useful
       anyway. Could be on a toggle switch?
   - If your signal doesn't reach the clipping threshold, then a hard
     clipper can also be used as clean boost.
   - Rather than providing optional boost; could be simpler to provide
     e.g. +6dB gain on all clippers, and an optional _pad_. Then we
     can choose whether to use it before or after clipping.
     - This also makes it easier to use the clippers with VCAs/LPGs
       that don't add gain.
   - Some of the folders can give big peaks - typically followed by
     soft clipping. This could be achieved with series
     normalisation...

     - e.g. chain 1: hard clip -> fold -> soft clip -> pad
     - chain 2: pad -> asymmetric fold -> deep soft clip

     Hmm, those two could be connected actually!

     - Soft clipping before a wavefolder could also limit the folder
       range, as long as they are appropriately calibrated.

     - hard clip -> asymm soft clip -> symm fold -> pad -> asymm fold
       -> symm soft clip

   - 4hp could be a squeeze for all those opamps!

*** Other folders
    - The Buchla wavefolder design is interesting as it doesn't use
      diodes; the clipping is done with op-amp rails.
      - Instead of subtracting the clipped voltage, it obtains a
        similar "point" waveform by tracking the current in the
        feedback loop of the clipping opamp.
      - Managed to get a circuitjs model of one stage working, see the
        folder.
      - This design could also be used to make a CV "dead spot" but
        surely diodes are cheaper.
      - The snag is that the slopes all depend on opamp resistors. Not
        a big problem for a musical wavefolder but might be tricky to
        design a precision splitter.
    - Was quite interested in the Auxren Tripsquad which is based on
      Serge Triple Waveshaper. The trouble with this transfer function
      is that it always rectifies the input. That's nice for saw waves
      but means cleaner/subtle applications are just impossible. I'd
      rather separate rectifier and folding stages for more versatility.
    - NLC Product uses wavefolders from Stork paper. I've separated
      out the first one as stork-folder-1 in Falstad
      folder. Interesting thing about these folders is that they are
      quite asymmetric by design; using op-amp to diff signal before
      and after diode drop.
      - This seems to require 3 op-amps total: input buffer/gainstage,
        diff stage, output buffer/gainstage. The diode voltage drop
        determines the size of the inverted/unfolded region. For Si
        diodes this is small and we need some gain-staging to use
        effectively with 5V p/p signals. We could eliminate the output
        buffer with a larger diode drop - using series diodes or blue
        LEDs?
*** Other shapers
    - Interesting tri-sin shaper discussed at MW
      https://modwiggler.com/forum/viewtopic.php?f=17&t=253285
      - For some reason this doesn't do any shaping in
        CircuitJS. Maybe the JFET is too ideal?
      - Otherwise seems quite forgiving. The original paper suggests
        using a trimmer on one side to get an exact resistance match
        (including internal resistances) and minimise even harmonics.
      - Would be nice to cascade this with a linear wavefolder to get a
        sine folder?

** Rectifier
   - I love the idea of the half-rectifying splitter combiner BHWR by
     CFM. The trouble is that it's passive; while that does enable
     bi-directional usage, it can lead to inconsistent behaviour.
     - How about a fully buffered version with explicit split/merge
       sections?
     - Could also achieve that by putting a quad buffer next to a
       BHWR. Can we get some other features?
       - Obvious tweak would be inverting input for NLC-style
         diff-rect.
         - taking diff of two half-rect stages is useful to get full
           rect. But to do the BHWR split/join trick we also need a
           straight sum option.
       - NE Pura Ruina is a multi-stage full rect. Presumably the way
         to make that work is put ac-coupling between the stages...

     - diff-rect: IN1, IN2 -> MAX(IN1 - IN2, 0), MIN(IN1 - IN2, 0)
       - NLC staple!
     - rect-diff: IN1, IN2 -> MAX(IN1, 0) - MIN(IN2, 0), MIN(IN1, 0) - MAX(IN2, 0)
       - With IN1 normed to IN2 this gives both polarities of full-rect
     - rect-sum: IN1, IN2 -> MAX(IN1, 0) + MIN(IN2, 0), MIN(IN1, 0) + MAX(IN2, 0)
       - This will do the reverse-connected BWHR trick, with the bonus
         of a complementary output

** Unipolar/bipolar shifter

   - An interesting circuit related to a clipper that I haven't really
     seen in Eurorack is the /clamper/. This uses a capacitor,
     resistor and diode to collect a bias voltage whenever the signal
     exceeds the diode forward-voltage. Because the effect is damped
     by the capacitor, this doesn't have to cause distortion: it
     shifts a bipolar signal to a unipolar one (+/- an input bias).
     https://electronicsreference.com/analog/clamper_circuit/
   - Of course, converting from unipolar to bipolar is just a very
     low-frequency RC high-pass filter.

   - Could be useful to change the time constant to suit a given input
     signal. At very small time constants we'll get distortion, with
     large time constants it will react slowly.

   - Easy to VC the reference point, but how useful is that? Basically
     an offset control, could also be achived by mixing output.
     - Might make an interesting distortion at audio rate?

   - For modules that only take +ve CV input this could be a nice
     supporting utility. Do I have any of those? Good for VCA/LPG
     signals?
     - Could use at CV input section of an Ardiuno-based module to
       intelligently handle both unipolar and bipolar inputs. Could be
       a bit confusing if unexpected though.

** Ultrasonic processing

   - Several interesting processes can be clocked by an ultrasonic
     oscillator, e.g.
     - mod-demod audio encoding
     - NLC digital filter simulator
     - Switched-cap filter (implemented in the LTC1064 chip)
       - Fabrica does it with a 4066 - what rate limit does that impose?
         https://github.com/vauxflores/Electronics/tree/master/Eurorack/Fabrica
       - CD4066B datasheet mentions control repetitions in MHz and
         "propogation delay" of around 20 ns - so should be just about
         fast enough for glitches to not dominate behaviour?
       - The technical purpose of switched-cap filters is for
         implementing very steep filters at accurate, high
         frequencies. They absolutely can go to lower frequencies, but
         the clock is running at 50x the cutoff frequency which is
         audible for low frequencies. Could also get aliasing?
     - Sampling processors: Sample/hold, shift register, "rungling"
       - Especially Squid Axon with its four clocks per new sample...
       - Can generate intentional aliasing by resampling at audio rate
         without a filter
     - Delta-sigma modulation (i.e. "1-bit" ADC/DAC)
   - Would be nice to have proper V/octave control over these so they
     can be related to audible VCO frequencies.
     - Or use a frequency multiplier? CD4046B phase-locked loop VCO
       can go up to 1.2 MHz.
       - It might make a lot of sense to use a CD4046B as the main VCO
         source actually. It's cheap and voltage-controllable.
   - This whole class of processing falls squarely into "hard to do
     in-the-box", which is really what I'm interested in modular for
     :-D
     - That being said, some oversampled Reaktor simulations might
       help with dialing in useful parameter ranges...
   - An interesting thing to introduce to this stuff in general is
     jitter. What's the best way to introduce small timing
     inconsistencies to a square wave oscillator?
   - For some switched-capacitor/resistor arrangements we can manipulate the effective value with the /pulse width/ of the switching.
     - A single high-frequency sawtooth clock could drive multiple filters using (relatively cheap/simple) VC comparators.
     - That seems like a great source of multiple somewhat lofi VCFs. What could we do with those?
   - Nearest thing out there seems to be WMD synchrodyne, which
     implements VCO -> PLL -> switched-cap filter
     - In practice the character/workflow is rather dominated by wobbly PLL wrangling
     - As usual for WMD, the module has tight control spacing and is a tad pricy at ~£350-400
     - Still, it seems like a pretty comprehensive take on placing
       that chain under VC. Good stuff, no point in going the same way.
   - It may be a bad idea to send ultrasonic signals through Eurorack
     inputs/outputs. The format is not really engineered for
     them. Generally the advice with HF is to keep paths very short in
     order to a) avoid capacitative losses b) avoid crosstalk with
     your other stuff.
     - The synchrodyne allows an external clock for the PLL but not
       for the filter. It does allow PLL output, but that has a wide
       useful range.
     - Maybe near-ultrasound is fine. But radio is not far
       away... (Strictly speaking, audio range is Very Low Frequency
       (VLF) radio.)
   - Barton SRV is a PWM-based filter, providing two resonant SVFs
     with multiple outputs.
     https://www.bartonmusicalcircuits.com/srv/ There is an inbuilt
     fixed oscillator and external clock input. Very nice!
     - Switched-resistor rather than switched-capacitor
       - The two are not so different really; switched-capacitors also
         replace resistors.
     - Demo vid suggests the LPF doesn't really "close" completely?
       Should be tweakable.
     - Audio-rate clock vowel sound demo is rad. I should build one of
       these.
   - PWM control seems an interesting general alternative to a vactrol
     or VCA. How about a PWM VCA? Presumably this is how PWM
     compressors work?
     - For a PWM VCA, just send the input signal through the
       PWM-controlled switch. At zero pulse-width you have a perfect
       "off" state. At 50:50 you have half gain, so will need some
       makeup.
     - What about nonlinear elements? Would this be one way to make a
       morphable transfer function?

** Oscillator

*** I can't believe it's not digital

    - Would love to have an analog oscillator that does FM synthesis
      in perfect ratios like a digital oscillator
    - The challenge is that while we might be able to get higher/lower
      partials from a reference wave by analogue means, they would
      then be coupled to the pitch of the reference wave and behave
      strangely when FM is applied.
    - Solution is to do phase modulation: mix signals into a good sine
      shaper. (Sinulator subassembly would be acceptable?)
      - This means that ideally the fundamental is a triangle wave and
        the modulators are sine waves. But triangles would be ok, not
        sure the difference is worth add lots of extra shapers for.
    - Would it be a nice control scheme to mix several partials into a
      master VC PM index (i.e. VCA to folder input mixer)?
      - Would be good it possible to break out partials to other VCAs
        and return them. Or just use another quad VCA...
    - Partials 2, 4 are easy from a triangle wave: full rectifier
      into ac-coupling and 2x gain.
    - How to achieve partials 3 and 5?
      - 3 could be done with a carefully calibrated wavefolder?
	- Actually this should work really well, for a triangle wave a
          single fold on each side gives x3.
	  - Which means that two wavefolders in series gives x9
	  - But one wavefolder with two folds (per side) gives x5 =)
      - A digital sine bank would be easier, but where's the fun in
        that? It would still avoid aliasing at high index, but there
        would be a bit of trouble if real FM is thrown into the mix.
      - The classic "wave multiplier" circuit uses a phase-locked loop
        and clock divider. The inbuilt VCO of a PLL is a square wave,
        so this setup would require an additional VCO. (Doesn't need
        to have good tracking though, PLL sorts that out.) This is a
        lot of chips for one partial...
    - This module is starting to sound a lot like "feed a
      harmonic/additive oscillator into FM Aid", which honestly isn't
      a bad idea. Would be quite a different control set in practice.
      - If partials are obtained from analogue fundamental, this does
        raise the question of whether the core VCO should even be part
        of the module.
      - I think it should be so that the calibration is saved. But
        maybe a normalised input would allow alternative signals to be
        introduced? Should provide a decent (non-VC) gain control for
        ad-hoc calibration then.
      - It's not so trivial to get a triangle wave from a DC-coupled
        saw input, because it needs to be offset by half the
        peak-to-peak voltage. i.e. it would be level dependent - not
        easy to dial out the DC offset "by ear" before subsequent
        shapers.
        - Saw-tri by wavefolding would be easier to set by ear, but
          maybe a more complex circuit
        - Or we just rely on the master VCO to take care of it.

    - So as a minimal building block to support this kind of
      synthesis, we could split the patch to:

      - VCO providing simultaneous saw and triangle waves at
        fundamental frequency. (Plenty of existing options!)

      - Tri -> 2x, 3x, 4x waveshaper with built-in mixer
        - or saw -> 1x, 2x, 3x, 4x triangles with tri mixer and saw
          thru

      - Saw-sine shaper with multiple folds (FM Aid, Sinulator)
        - These also provide CV over FM depth

** VCAs

*** PWM
    - See ultrasonic processing notes
    - PWM VCA is actually pretty simple, but unusual in audio paths
      [due to a) clock noise b) availability of proper VCAs].
      - High-speed saw VCO -> VC comparator -> FET/CMOS analog switch -> lowpass/slew
      - Potential benefits are linearity and ability to mess around
        with clock interactions.
    - A neat module could be:
      - inbuilt clock which can be bypassed by ext saw input
      - Saw-multiplying rectifier series (Could use rotary switch or
        CMOS to select number of stages!)
      - Comparator with external CV creates PWM signal
      - Simple passive low-pass/slew with a few switchable frequencies
        (or manual pot?)
	- No need for VC on this, run into an external filter/slew limiter
          if you want to get fancy.
      - Multiple VCAs can run off the same clock; cascaded mixing
        outputs would be nice.
	- In which case they need individual slew limiters but would
          make sense to control them together. Analog-switched
          presets would be much easier than a pot then!
    - There are some possible variations on the switching element: as
      well as an open/closed switch this could be a dual-throw between
      resistors or a control signal to an
      optocoupler. (i.e. optocoupler to ground acting as a chopper.)
    - PWM signals can be used with logic gates: (N)OR for a "bypass",
      (N)AND for an "enable/mute", XOR for pseudo-ring-mod of multiple
      control signals (with gate it would become "invert" which is
      also a pretty cool option).
    - Should also be rather cheap in ICs! Can use a hexinverter as
      oscillator and comparators? CMOS switches and XOR are
      cheap. Most complicated part is looking to be the slew
      limiters.
      - What is a cheap/easy way for one panel control to set four
        slew limiters? The sections don't have to be perfectly
        matched, how about an LED/LDR arrangement?
      - The catch is that the classic relaxation oscillator doesn't
        make a nice linear sawtooth; PWM won't be linear.
	- Won't matter in many applications but would be a problem for
          ring mod.
	- But what about using a comparator with the "triangle" wave?
          Will that cancel out?
	  - Playing around in numpy it looks like this doesn't
            _perfectly_ cancel out, but it's not that bad. Why were we
            focused on saw waves again? Ramps PWM just as well.
    - Simple RC low-pass: series resistor followed by capacitor to
      ground. Could be issue with gain interaction between this
      resistor and an inverting output buffer. Maybe go non-inverting?

      - f = 1/(2 pi R C) = (/ 1 (* 2 3.14159 1e7 1e-9)) = 16 Hz
      - f = 1/(2 pi R C) = (/ 1 (* 2 3.14159 1e5 1e-9)) = 1.6 kHz
      - f = 1/(2 pi R C) = (/ 1 (* 2 3.14159 1e3 1e-9)) = 160 kHz

      - i.e. a 1nF capacitor and 100k resistance would give a 1.6 kHz
        cutoff, about as low as we'd ever want to go, and 1k
        resistance would take that to 160 kHz, higher than we'll ever
        need. A 5506/5516 LDR ranges from around 5k to 500k, so quite
        comparable. Could tune the range with additional
        series/parallel resistors if necessary.

    - Bipolar / ring-mod adaptation would be quite simple: chop an
      inverted input signal at opposite polarity. Could do this with
      NOT+SPST (mixing outputs) or by replacing CMOS SPST with SPDT
      chip (no mix required!). Either way, they can share an output
      filter and VCA mode is enabled by simply disconnecting the
      inverted path.
      - The biggest challenge might actually be shifting the CV input
        range between 0-5V and +/-5V. Would be nice if that was on a
        manual DPDT that also disconnects the inverted path.
      - With decent clock/filter settings that could actually be quite
        a decent ring mod? Nice and linear.


*** Opto-isolated
    - Modern opto-isolators on chips are faster, more linear and more
      consistent than traditional vactrols. They seem under-used in
      synthesiser design?
    - Some accounts online of good experiences with H11F1 optocoupler
      chip. Quite linear withing a certain range of operation, can
      also add distortion beyond that.
      - Account here of using one for a Doepfer CV mod; needs a simple
        LED driver circuit (opamp CV input buffer + transistor current control)
        http://navsmodularlab.blogspot.de/2013/01/a-143-1-modification.html
    - NLC DP Filter calls for TLP521-2 dual optoisolator; the notes
      list many alternatives, with roughly 50:50 split on whether they
      are suitable for that circuit.
